### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [rslavin/af-magic-dynamic#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by rslavin** [comment]
I added some screenshots in cb2674757e558cc76bd97ee4b18fe63a05c26b59 and submitted a [pull request](https://github.com/unixorn/awesome-zsh-plugins/pull/1055) to your repo. 

Cheers!

**Comment by unixorn** [comment]
Cool, thanks!
